### PR TITLE
Ar fiji

### PR DESCRIPTION
**Pull request by aring97**
git fetch --all
git checkout AR-Fiji
look for completion of content

### CODE REVIEW

**Comment by Michael-Tyler** [comment]
line  13 is missing the site title "balrogs big getaway"
line 56 the photo isn't linked right, I checked it should be `images/fiji/Sleeping_Giants.jpg`
line 71 photo link missing .jpg

**Comment by meesterbaumer** [comment]
Looks like 2 photos are not properly loading. 
Also site title is missing

**Comment by Michael-Tyler** [comment]
looks good

**Comment by meesterbaumer** [comment]
Looks great now!! You can merge

**Pull request merged**
