### PR TITLE
Je taiwan content

### PR DESCRIPTION
**Pull request by skratz17**
1. `git fetch --all`
2. `git checkout je-taiwan-content`
3. Go to `taiwan.html`
4. Verify that all landmarks and people have descriptions written for them.
5. Verify that the people include Cai Yingwen, Ma Ying-jeou, Chen Shui-bian, and Chiang Kai-shek.
6. Verify that the Chinese names of each city, landmark, and person are appearing in your browser, visible in parentheses following each English name in the `<h3>` elements within each card.

### CODE REVIEW

**Comment by gavinschriver** [comment]
All looks good to me! Although I can't lie, kinda bummed it looks like my man Chang got the boot
:<

**Comment by skratz17** [comment]
Whoops, I actually realized that the project description called for explicitly heads of state in the notable people section, not just famous people. So I have gotten rid of Ang Lee and Jay Chou, and added in some politicians. Your boi Chiang is back, Gavin.

New verification steps are:

1. `git fetch --all`
2. `git checkout je-taiwan-content`
3. Go to `taiwan.html`
4. Verify that all landmarks and people have descriptions written for them.
5. Verify that the people include Cai Yingwen, Ma Ying-jeou, Chen Shui-bian, and Chiang Kai-shek, and that Ang Lee and Jay Chou have been removed.
6. Verify that the Chinese names of each city, landmark, and person are appearing in your browser, visible in parentheses following each English name in the <h3> elements within each card.

**Comment by Michael-Tyler** [comment]
looks good

**Comment by gavinschriver** [comment]
dig it

**Comment by meesterbaumer** [comment]
Looks great!  Love the characters

**Comment by aring97** [comment]
All good

**Pull request merged**
