### PR TITLE
changed tuvalu.html to index.html

### PR DESCRIPTION
**Pull request by aring97**
git fetch --all
git checkout AR-Fiji
see the tuvalu.html has been changed to index.html

### CODE REVIEW

**Comment by skratz17** [comment]
Looks good except for one thing:

1. The `<h2>` landmarks list header does not have the "sectionTitle" class attached to it so is appearing smaller than other heading.

**Comment by skratz17** [comment]
Looks good to me.

**Comment by gavinschriver** [comment]
Yep looks good, merge it

**Comment by Michael-Tyler** [comment]
looks good ready to merge

**Pull request merged**
