### PR TITLE
Gs component setup

### PR DESCRIPTION
**Pull request by gavinschriver**
1. `git fetch --all`
2. `git checkout gs-componentSetup`
3. Look at the romania page in browser, make sure all elements are rendering from romaniaMain.js imports (navBarLinkList, introList, cityList, headOfStateList)
**messed with icelandMain.js while testing so it's not where it was on Mike B's last commit**

### CODE REVIEW

**Comment by Michael-Tyler** [comment]
looks good, everything works.

**Comment by skratz17** [comment]
1. In `cityHTMLRepresenter.js`, the `section` element is missing a class of `card` (in addition to `city` which it already has.
2. In `cityHTMLRepresenter.js`, the `img` element is missing a class of `city__image`.
3. You missed a closing quotation in the appending of HTML at the end of `cityList.js`. The class of `sectionTitle` on the `h2` needs a closing quotation mark.
4. You are missing a closing `a` tag in `navBarLinkHTMLRepresenter.js`.
5. You also included a new `section` element in `navBarLinkList.js` that wasn't present in our original project. If you got rid of this `section` wrapping the `navBarLinkListHTML` that would probably make the navbar render as it did in our original project (and also fixed the issue above in number 4).

**Comment by gavinschriver** [comment]
Fixed stuff jacob pointed out

**Comment by skratz17** [comment]
All looks good now 👍

**Pull request merged**
