### PR TITLE
Mt tuvalu scripts

### PR DESCRIPTION
**Pull request by Michael-Tyler**
1. `git fetch --all`
2. `git checkout mt-scripts-tuvalu`
3.  check for data providers to be filled in and exporting copies properly.

### CODE REVIEW

**Comment by skratz17** [comment]
1. In `tuvaluCityProvider.js`, the property name in your objects should be `imageAlt`, not `iamgeAlt`.
2. In `tuvaluHeadOfStateProvider.js`, the property name in your objects should be `description`, not `desrciption`.

**Comment by skratz17** [comment]
The `description` fix looks good, bou still need to fix the `iamgeAlt` issue on the last three objects in the `tuvaluCities` array in `tuvalyCityProvider.js`

**Comment by skratz17** [comment]
Looks good to me now. 👍

**Comment by gavinschriver** [comment]
look gooooodd 👍

**Pull request merged**
