### PR TITLE
GS Romania Content

### PR DESCRIPTION
**Pull request by gavinschriver**
1. `git fetch --all`
2. `git checkout gs-RomaniaContent`
3. Make sure Banner Image + Country Name are in first area, then 2 city cards, 2 landmarks + descriptions, 2 heads of state w/ descriptions in main area

### CODE REVIEW

**Comment by skratz17** [comment]
Looks good, except for one minor thing:

1. I am not seeing a landmark name (in the `<h3>`) for the second landmark in the landmarks list.

**Comment by skratz17** [comment]
Great, I'm seeing the landmark name now and the rest of the content all looks good to go as well!

**Comment by meesterbaumer** [comment]
Looks great go ahead and merge

**Comment by Michael-Tyler** [comment]
looks good

**Pull request merged**
